env: bq3

env_args:
  game_agent_id: 5
  game_map_id: 5
  owner: 1

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 10050000
