env: bq

env_args:
  game_agent_id: 0
  game_map_id: 0
  owner: 0

learner_log_interval: 20000
log_interval: 20000
runner_log_interval: 20000
t_max: 10050000
test_interval: 20000
test_nepisode: 24
test_greedy: True
