env: bq

env_args:
  game_agent_id: 0
  game_map_id: 2
  owner: 0

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 10050000
